### ISSUE TITLE
Warn "subpath folder mappings" in exports field

### ISSUE THREAD

**Issue by sapphi-red** [bluwy/publint#1]
This is a nice tool 💙

---

subpath folder mappings are not supported by Vite.
https://vitejs.dev/config/#resolve-conditions:~:text=Resolving%20subpath%20exports,subpath%20patterns%20instead.

Also it is deprecated. (and is removed in 17.x+?)
https://nodejs.org/docs/latest-v16.x/api/packages.html#subpath-folder-mappings

Example package: https://publint.bjornlu.com/@ringcentral/juno@1.11.5

**Comment by bluwy** [comment]
Ah yeah that should definitely be caught too. Think it might be a simple check for trailing slashes. And also it currently falsely reports that the file doesn't exist, which can be fixed along the way.

**Comment by bluwy** [comment]
Added support for this in [v0.1.0](https://github.com/bluwy/publint/releases/tag/v0.1.0). You should see the warnings now with the same link.
