### ISSUE TITLE
Bump `npm-packlist` from `5.1.3` to `8.0.2`

### ISSUE THREAD

**Issue by kravetsone** [bluwy/publint#102]
![image](https://github.com/bluwy/publint/assets/57632712/e01cecfa-e210-41e9-9479-a1b0848b8d26)
![image](https://github.com/bluwy/publint/assets/57632712/154c64f8-db59-4350-91be-1cbfa8af8d36)
https://npmgraph.js.org/?q=npm-packlist@5.1.3

vs

![image](https://github.com/bluwy/publint/assets/57632712/d0771e8e-f861-4a35-a409-8ec0676b6285)
![image](https://github.com/bluwy/publint/assets/57632712/26bedc08-3bd1-4810-ade8-b2d907a9b2d1)
https://npmgraph.js.org/?q=npm-packlist

**Comment by bluwy** [comment]
Thanks, but I'm currently tracking this at #11.
