### ISSUE TITLE
Update message for required `type`

### ISSUE THREAD

**Issue by benmccann** [bluwy/publint#103]
I've noticed publint has started suggesting `"type": "commonjs"` should be present in all packages because `"type": "module"` could become the default in the future. However, I don't think it's true that `"type": "module"` could become the default. When I read through the links in the message they don't actually say that and it seems pretty much impossible that it could be done as it would break so many projects.

**Comment by lachlancollins** [comment]
Hi @benmccann , this was my suggestion in #83 regarding `--experimental-detect-module` - the recommendation from the Node.js team was the following:

> Detection increases startup time, so we encourage everyone—especially package authors—to add a type field to package.json, even for the default "type": "commonjs".

I agree its very unlikely that `"type": "module"` will ever become the default, but I do think it's possible that Node will make ``--experimental-detect-module` enabled by default.

**Comment by benmccann** [comment]
Ah, I see. Maybe we should update the message. Right now it says:

> Environments may incorrectly identify a CJS file as ESM in the future.

But it sounds like that's not the risk that we're worried about, but rather that it increases startup time which makes more sense to me.
