### ISSUE TITLE
Update npm-packlist

### ISSUE THREAD

**Issue by bluwy** [bluwy/publint#11]
npm v9 introduced a breaking change to `npm-packlist` ([release notes](https://github.com/npm/npm-packlist/releases/tag/v6.0.0)). However yarn v3 and pnpm v7 have not adopted this yet.

This issue tracks when yarn and pnpm start moving towards the new pack logic before we update it.

**Comment by bluwy** [comment]
`inflight` is now deprecated and would be good to bump this to prevent the warnings.

```
publint 0.2.8
└─┬ npm-packlist 5.1.3
  └─┬ glob 8.1.0
    └── inflight 1.0.6
```

**Comment by bluwy** [comment]
Thinking about this today, I think it's better to take a step back and not get involved by manually invoking packing. Different package managers have different ways of packing files and packing `package.json`, they can pack the `publishConfig` field differently too:

- npm: https://docs.npmjs.com/cli/v10/using-npm/config#config-settings
- yarn: https://yarnpkg.com/configuration/manifest#publishConfig
- pnpm: https://pnpm.io/package_json#publishconfig

This means `publint`'s current `publishConfig` detection is non-standard (follows pnpm).

# Proposed solution

Create a new option:

```ts
pack: 'auto' | 'npm' | 'yarn' | 'pnpm' | { command: string } | { tarballPath: string }
```

`auto` is the default, which will find a lockfile locally to detect either `'npm' | 'yarn' | 'pnpm'`. The command will be executed and output into an os temporary directory, which we'll unpack and then delete. If `{ command: string }`, is passed, it'll run that pack command instead. If `{ tarballPath: string }` is passed, it'll simply use that tarball.

After unpacking the tarball, the paths should be normalized to match the existing filesystem paths. The main data we need is really only the published `package.json` and the file paths packed. It's safe to assume package manager that change more than that?

**Comment by charlyoleg2** [comment]
Would be great to update the dependency _npm-packlist_! I get 2 _warn depreciated_ and 3 _high vulnerabilities_ warnings because of that dependency.

**Comment by SymphonySimper** [comment]
> Would be great to update the dependency _npm-packlist_! I get 2 _warn depreciated_ and 3 _high vulnerabilities_ warnings because of that dependency.

+ 1

**Comment by bluwy** [comment]
Perhaps it makes sense to cut a breaking minor for now to resolve this. I haven't got the time to do a better overhaul.

**Comment by bluwy** [comment]
I looked into bumping this today and it looks like it also requires `@npmcli/arborist` to be used along-side, and unfortunately it's extremely large. [162 dependencies](https://npmgraph.js.org/?q=%40npmcli%2Farborist) and [13.5MB total install size](https://packagephobia.com/result?p=%40npmcli%2Farborist).

This is a dealbreaker for me, so I'll hold off bumping it for now and await the proper solution proposed at https://github.com/bluwy/publint/issues/11#issuecomment-2176160022

> I get 2 _warn depreciated_ and 3 _high vulnerabilities_ warnings because of that dependency.

I only got deprecated warnings. No vulnerability warnings on my end:

```bash
bjorn@Bjorns-MacBook-Pro publint-vul % npm i publint
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated glob@8.1.0: Glob versions prior to v9 are no longer supported

added 17 packages in 2s

2 packages are looking for funding
  run `npm fund` for details
bjorn@Bjorns-MacBook-Pro publint-vul % npm audit
found 0 vulnerabilities

```
