### ISSUE TITLE
[Feature Request] Add a way to lint locally uploaded build artifacts

### ISSUE THREAD

**Issue by la55u** [bluwy/publint#14]
By enabling the upload of arbitrary local build artifacts, those packages that are otherwise published privately could also be linted. I realize that this directly conflicts with the name of the project but I think it would be a very useful feature.
Thank you, awesome project anyway!

**Comment by bluwy** [comment]
I believe this works now. You can run `npx publint` in the private package project after a build to validate the build artifacts. Or if you want to lint an installed package, `npx publint ./node_modules/pkg` should work too.
