### ISSUE TITLE
Expose `printMessage` util for usage JS usage

### ISSUE THREAD

**Issue by ArnaudBarre** [bluwy/publint#23]
I want to integrate this into https://github.com/vitejs/release-scripts via the JS API and it would be nice to expose some of the code use in the CLI to simplify integration there.

**Comment by bluwy** [comment]
Yeah I think this make sense. We could export this so it works in node/locally only.

**Comment by ArnaudBarre** [comment]
Thanks! I'm watching releases and I will use it when the next version is released 🙂

**Comment by bluwy** [comment]
Published v0.1.9! I was planning to do something before the release, but I forgot about it, so I just published anyways 😄
