### ISSUE TITLE
Ignore `.mjs` check for `browser` export condition

### ISSUE THREAD

**Issue by bluwy** [bluwy/publint#3]
https://github.com/brillout/json-serializer/issues/9#issuecomment-1302372663

**Comment by brillout** [comment]
The thing is that it's always bundlers that process `browser` exports. So, as long as bundlers are fine with it, then we can ignore this rule.

I've projects not respecting this rule and Vite, Parcel, and webpack all seem to be fine with it.

**Comment by bluwy** [comment]
Fixed in v0.1.2
