### ISSUE TITLE
printMessage API documentation

### ISSUE THREAD

**Issue by huozhi** [bluwy/publint#37]
Then `printMessage` requires two arguments, message and package json, but document is missing `pkg` argument.

Another is `printMessage` returns the string, it sounds more like `formatMessage` instead of actually printing. Maybe considering a rename or adding a new API `formatMessage` and then deprecate `printMessage` in next big release

**Comment by bluwy** [comment]
You're right, I forgot to document about the second param. The rename makes sense too, it was initially exposed from an internal util. We could probably do the first part for now to fix this though.

**Comment by huozhi** [comment]
Thanks for updating the docs, is there any plan to rename the API in the short future as well? Do you want me to file another issue to track that?

**Comment by bluwy** [comment]
Yup, would appreciate if you can open a new issue for it so we can track it!
