### ISSUE TITLE
Warning as error in CLI mode

### ISSUE THREAD

**Issue by dubzzz** [bluwy/publint#38]
Having the ability to mark warnings as errors when running `publint` through the CLI might be pretty useful. Some lint rules such as types not being properly defined via exports come as warnings and being able to promote them to errors (not just them, but just say we forbid errors and warnings) would be great.

I was thinking about some flags such as `--warning-as-error` or `--max-warnings num` (see https://eslint.org/docs/latest/use/command-line-interface#max-warnings).

**Comment by bluwy** [comment]
Make sense to me 👍 Maybe a `--strict` option would be nice too. I should probably re-evaluate what gets to be a warning and error in the next major, they're a bit inconsistent now.

**Comment by bluwy** [comment]
The `--strict` flag is supported in v0.1.12
