### ISSUE TITLE
Support for `.cjs.native.js`

### ISSUE THREAD

**Issue by benmccann** [bluwy/publint#41]
We've been having issues with reports about `@apollo/client` not working in SvelteKit/Vite.

Publint reports issues with the package: https://publint.dev/@apollo/client@3.7.14

But the Apollo folks say it's not an issue:
![Screenshot from 2023-05-12 10-05-52](https://github.com/bluwy/publint/assets/322311/5aac3cf7-f723-4c9e-b80c-369c909eed89)

**Comment by bluwy** [comment]
Make sense to me 👍 Didn't know about this React Native convention.

**Comment by bluwy** [comment]
Fixed in v0.1.12
