### ISSUE TITLE
Consider support custom rules and rule's level.

### ISSUE THREAD

**Issue by icy0307** [bluwy/publint#45]
Thx for the awesome library!
Can the users add custom rules and change the severity of the rules for specific packages, by some kind of configuration files?
kinds of like eslint?

**Comment by bluwy** [comment]
Hey 👋  At the moment, you can't do that as I'd like to keep the library opinionated with best practices. Adding new rules via some sort of plugin system had crossed my mind too, but I think it's still a bit early to plan that out as there's a lot of features I'd like to build first. A config file might also come naturally as we get to those features.

So besides the "change severity" part, the rest should come in the long term eventually.

**Comment by icy0307** [comment]
By adding custom rules and suppressing errors to the designated level, a lot of practical things could be achieved.
For example, I worked for large private front repo, by pub lint every prod dependency and indirect dependencies in `package.json `,  bundle size could be reduced significantly.
Here are some rules that might help:
1.  ESM_FORMAT_MUST_BE_PROVIDED. 
As a front-end project, all packages in this project must support an esm version, which will significantly reduce bundle size.
2. NO_FIXED_PACKAGE_VERSION. 
Fixed package version is the culprit of multiple versions of a project, hence causing large js files size, which leads to performance problems.
3. HAD_DEPENDENCIE_BUT_NO_IMPORT. 
If the package has a prod dependency but has no `import` or `require` syntax in corresponding files, it suggests that this dependency is redundant, or this package bundles ite node modules in the final output. The first scenario is bearable and can be treated as a warning, and the latter must be treated as an error.
4. PREFER_PRESERVE_FILE_STRUCTURES.
When file size is larger than certain limits. Instead of a big fat index file, the original file structures should be provided, so that apps which use these libraries can leverage the use of tree-shaking for esm or `babel-plugin-import` for cjs files.

By adding `pub-lint` project in CI, problems can be found in early stages and forbid certain request get merged if it invalids these rules.

In order to do that, here are some rules that need to be suppressed as warnings:
1. file_does_not_exist in certain scenarios.
`rxjs@7.8.1`,  the latest rxjs, throw an error in the line : 
```
// File does not exist ([More info](https://publint.dev/rules.html#file_does_not_exist))
"types":"index.d.ts",
```
However,  in its export field, the correct types information can be found.
```
"exports": {
".": {
"types":
"./dist/types/index.d.ts"
,
...
},
```
So even though the "types" field, it might as well be treated as a warning.
2. FILE_INVALID_FORMAT can be turned off or turned into suggestion.
`@mui/material`, `@shopify/polaris`, and `antd ` , all throws `FILE_INVALID_FORMAT ` warning because lack the  "type": "module" field. pub-lint outputs every file as a warning which causes the overall log unreadable.

**Comment by icy0307** [comment]
> I'd like to keep the library opinionated with best practices
May I ask what are these practices?

**Comment by bluwy** [comment]
> 4\. PREFER_PRESERVE_FILE_STRUCTURES

I'm not sure if this is true as treeshaking doesn't depend on the file structure.

> 1. file_does_not_exist in certain scenarios.
>    `rxjs@7.8.1`,  the latest rxjs, throw an error in the line :

That's a bug tracked at https://github.com/bluwy/publint/issues/42

> FILE_INVALID_FORMAT can be turned off or turned into suggestion.

I don't think it should be turned off because it prints too many warnings. Probably a more concise warning message would be better instead.

> May I ask what are these practices?

They're largely documented at https://publint.dev/rules.

---

The goal with `publint` so far is to provide sensible lint rules to most npm packages. So scoping it down to a set of rules that fits your preference isn't something I've planned for. Maybe it could be nice to achieve that in the future, but I'm not sure how that will look yet.

**Comment by bluwy** [comment]
Closing this for now as it's out of scope for its current state, but there could be a possibility that publint becomes pluggable and more flexible in the future. There's still a lot more plans for publint that I don't think we can settle on a plugin API yet. Thanks for kicking of the conversation!
