### ISSUE TITLE
Linting package does not end when there's a invalid JSON file

### ISSUE THREAD

**Issue by sapphi-red** [bluwy/publint#5]
https://publint.bjornlu.com/resolve@1.22.1

It stops with "Linting package..." with the error below.

> Uncaught (in promise) SyntaxError: Expected property name or '}' in JSON at position 2

**Comment by bluwy** [comment]
`resolve` publishes their test files for some reason but I made this more lenient too.

https://cdn.jsdelivr.net/npm/resolve@1.22.1/test/resolver/malformed_package_json/package.json
