### ISSUE TITLE
Feature: add select to switch the version

### ISSUE THREAD

**Issue by btea** [bluwy/publint#56]
Sometimes there is a problem in the new version, but the previous version is no problem, add a select to quickly switch the version to easily locate which version is the problem.

I can try to create a PR if you think it works.。

**Comment by bluwy** [comment]
Hi, do you mean the publint version, or the package version? Changing the publint version is a little tricky since they are code shipped to specifically handle a version of publint, e.g. converting the results to human-readable messages.

If you mean the package version, that's definitely a welcome change! I actually experimented that a bit last week, but it's hard to get the design right. I could also push the wip branch up for reference.

**Comment by btea** [comment]
Yeah, I mean the package version.

**Comment by bluwy** [comment]
Sounds great, feel free to send a PR if you'd like. I can also push my branch later when I get to my laptop, but it's a bit outdated now.

I'm currently working on some design touch ups to the site locally that's no published yet, in case you're seeing some things different.

**Comment by bluwy** [comment]
Here it is: https://github.com/bluwy/publint/tree/switch-version. It's actually kinda almost there I think, but needs a little polishing.

**Comment by btea** [comment]
I tried it and it looks amazing! 👍

However, there is a little problem, when the version is switched, there will be page switching flashing, which does not look so smooth.

![publint](https://github.com/bluwy/publint/assets/24516654/05d571ea-5b63-4c90-914f-8b6217114238)

**Comment by btea** [comment]
I'm relatively new to Sevelte. I tried a similar effect directly using the `select` tag locally, and the above situation does not occur when switching. I found that you added a new component `PackageVersion.svelte`, perhaps because of it? 

Since my local logic is written directly in the `Package.svelte` component, there is this guess. 🤔

You're making overall improvements to the site, and I think it's better to keep your rhythm, so I'm not going to make changes, but I'll keep looking at the code.

**Comment by bluwy** [comment]
Awesome. Yeah I tried with `select` first too, but unfortunately when we lazily fetch the options, Safari doesn't update the list automatically. It was also hard to style it, so I went with the manual select implementation.

**Comment by btea** [comment]
The compatibility handling of native `select` is a real headache. 🤦‍♂️

**Comment by bluwy** [comment]
0012a81 should implement this and will release the site later tonight. Closing this for now.

**Comment by btea** [comment]
The new site style looks so cool! 👍
