### ISSUE TITLE
The version switch doesn't seem to work

### ISSUE THREAD

**Issue by btea** [bluwy/publint#57]
![b](https://github.com/bluwy/publint/assets/24516654/e380b83c-7d7a-46c6-8a16-5ed032714a22)

**Comment by bluwy** [comment]
My bad, was only testing in Safari 😅 Gonna fix this and thanks for testing!

**Comment by bluwy** [comment]
Looks like there's also a weird CORS error in Firefox

**Comment by bluwy** [comment]
Fixed in 64928ef
