### ISSUE TITLE
Consider dropping EXPORTS_GLOB_NO_DEPRECATED_SUBPATH_MAPPING when it occurs before an equivalent `"./*"`

### ISSUE THREAD

**Issue by andrewbranch** [bluwy/publint#62]
https://publint.dev/tslib@2.6.1 issues a warning on the export subpath `"./"`, which we added and kept for whatever versions of Node (probably EOL and/or patched now) supported the trailing slash and _not_ the trailing star. tslib _also_ declares an equivalent `"./*"` key _before_ the `"./"` key, so the latter one, while deprecated, is kept intentionally and isn’t doing any harm.

**Comment by bluwy** [comment]
I think we can definitely lower it as a "suggestion" type if it's only for compat and has the adjacent key. I'd like to keep the message still since the trailing slash support has been long EOL, and the suggestion could be kept as a nudge for the next major.
