### ISSUE TITLE
Add the function of quickly jumping to a specified location

### ISSUE THREAD

**Issue by btea** [bluwy/publint#67]
Taking `axios` as an example, its `package.json` content is very long. When the suggestion information shown in the figure below appears, I hope to quickly jump to the specified detailed information location.

Therefore, I think it would be very convenient if I could bind a click event to `1 suggestion` and jump to the detailed information after clicking.

![image](https://github.com/bluwy/publint/assets/24516654/ca967ab5-feb2-46e6-a1cc-0db0fc0bea8e)

**Comment by bluwy** [comment]
Sounds good to me 👍 We can make those buttons which scrolls to the first suggestion/warning/error.

**Comment by btea** [comment]
Yes, that's what I thought.
