### ISSUE TITLE
Skip "The package publishes internal tests or config files" check?

### ISSUE THREAD

**Issue by ljharb** [bluwy/publint#81]
I intentionally publish tests with all of my packages. Could there be an option that skips this check?

**Comment by bluwy** [comment]
Is there a reason you publish tests?

**Comment by ljharb** [comment]
Yes, because since time immemorial, `npm explore foo && npm install && npm test` is supposed to work, so that you don't need an internet connection to run your deps' tests. That it's become fashionable not to publish tests doesn't change that.

Either way, that's the way all 450+ of my packages are built, and I'd love to use this tool without having to wade through these "suggestions".

**Comment by bluwy** [comment]
Thanks for the explanation. I've not quite used this workflow before, but it still feels like a rare thing to do these days, and I'm not sure if it's fair for users to pay the bandwidth price upfront for this.

At most they'd only patch a certain piece of code regardless of tests to get it work. And if they're considering submitting a fix, they'd need to clone it down anyways.

Also wouldn't `npm install` still require a network connection?

**Comment by ljharb** [comment]
Nope, `npm install` works from cache.

Regardless, I'm not asking to change the default, I'm asking for a command line option so _i_ can skip it.

**Comment by bluwy** [comment]
You can use `--level warning` to only log warnings and errors.

**Comment by ljharb** [comment]
I don't want to hide all suggestions, just this specific one.

**Comment by bluwy** [comment]
At the moment I don't have plans to support ignoring certain messages yet.

**Comment by bluwy** [comment]
Closing this for now as I'd like the library to be more opinionated on certain practices, but I might revisit a more fine-grain ignore option once I figure a plugin implementation for the library, which then ignoring certain "rules" like eslint could be more useful.
