### ISSUE TITLE
Suggest adding `"type"` field to all packages

### ISSUE THREAD

**Issue by lachlancollins** [bluwy/publint#83]
Hi there, I was reading through the Node v20.10.0 [release notes](https://nodejs.org/en/blog/release/v20.10.0) and noticed the following regarding experimental CJS/ESM detection:

> We hope to make detection enabled by default in a future version of Node.js. Detection increases startup time, so we encourage everyone — especially package authors — to add a type field to package.json, even for the default "type": "commonjs". The presence of a type field, or explicit extensions such as .mjs or .cjs, will opt out of detection.

I'm wondering if it would be a good idea for publint to recommend that all packages have a `"type"` field, since it seems Node will shift away from `"commonjs"` as the default. I'd imagine this would be a suggestion rather than a warning.

**Comment by bluwy** [comment]
I think that makes sense 👍 It might be safer to wait till node v22 to see if they're settled on it before implementing it here. It's going to suggest that for a lot of packages.

I'll add this as an enhancement for now, and when v22 lands (around April/May 2024) we can implement it.

**Comment by lachlancollins** [comment]
> I think that makes sense 👍 It might be safer to wait till node v22 to see if they're settled on it before implementing it here. It's going to suggest that for a lot of packages.
> 
> I'll add this as an enhancement for now, and when v22 lands (around April/May 2024) we can implement it.

Hi @bluwy , just letting you know this was also just added to Node v20.10.0 - I've updated the post above to link to the new release notes.

**Comment by bluwy** [comment]
Ah neat. If it's already in node 20 (LTS), then it seems like there's a good reason to push towards it now.
