### ISSUE TITLE
feature requerst: badges like shields.io

### ISSUE THREAD

**Issue by reslear** [bluwy/publint#94]
implement badges like https://shields.io/badges

https://github.com/arethetypeswrong/arethetypeswrong.github.io/issues/161

**Comment by bluwy** [comment]
Thanks! However, this is something I don't plan on yet as it includes server costs to run the package and lint them on the server-side. I also gave my thoughts on it at https://github.com/bluwy/publint/issues/89#issuecomment-1870802009.

For now, this isn't something I plan to do builtin, but I don't mind if 3rd-party services wants to implement badges using publint.
